language: php

services:
  - postgresql

addons:
  postgresql: "9.6"

# Allows using containers
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache

# Base versions to test raw with the Symfony latest version.
php:
  - 7.1
  - 7.2
  - 7.3

# Update composer, and update Symfony version depending on the matrix
before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi
  - mkdir -p build/logs

install:
  # Database creation
  - psql -c 'create database symfony;' -U postgres
  # Install application
  - composer install --verbose
  # Database migration
  - php bin/console doctrine:migrations:migrate
  # Data test installation
  - php bin/console doctrine:fixtures:load --env=dev --fixtures=src/DataFixtures

# Run script and log coverage in the "build" directory
script:
  - php bin/console server:run
  # Unit test
  - php bin/codecept run unit
  # Functional test
  - php bin/codecept run functional

# After a build, sends a notification to this e-mail with the build results.
notifications:
  email:
    recipients:
      - alexandre.tranchant@gmail.com
    on_success: never
    on_failure: change
